# fly.toml file generated for bayeue on 2022-08-02T03:14:50+07:00

app = "bayeue"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  MY_SPECIAL_ENV="bayeue"
  MAX_PLAYER_COUNT=15
  DBNAME="db_bayeue"
  DBUSER="root"
  DBPASS="root"
  DBHOST="my-mysql.internal"
  DBPORT="3306"
  JWTSecret="bayeue_secret"
  CLOUD_NAME="dt91kxctr"
  API_KEY="653888772144598"
  API_SECRET="G1AQLgaUxPOhc3igk1XNYtvL7S4"
  UPLOAD_FOLDER="go-bayeue"
  Xendit_API_Dev="xnd_development_I0guK5bOcQB3AVQ8pYUXMtXltsVvfqsyPU2dz1RJvTDNVrsLVxqC8K0KJc3YhlZE"
  OTP_Xendit_Callback="BjVVRO8eKgceve38jmqm6twtK9YLjtAfk7CbJLxfiToTilHX"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"